global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  width: 15
  height: 15
  origin_x: -7.5
  origin_y: -7.5
  rolling_window: true
  resolution: 0.01
  plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
  inflation:
    inflation_radius: 0.5
    cost_scaling_factor: 8.0