local_costmap:
  update_frequency: 10
  publish_frequency: 10
  transform_tolerance: 0.4 #0.25
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.01
  plugins:
      - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}
      - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
  inflation:
    inflation_radius: 0.5
    cost_scaling_factor: 8.0