TrajectoryPlannerROS:
  max_vel_x: 0.2 #0.2
  min_vel_x: 0.1 #0.1
  max_vel_theta: 0.4 #0.35
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.25

  acc_lim_theta: 0.25
  acc_lim_x: 2.5
  acc_lim_Y: 2.5

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.02 #0.15
  yaw_goal_tolerance: 0.05 #0.25